<h3>Na swoje księgi</h3>

<p>
    Nie dbają moje papiery<br />
    O przeważne bohatery;<br />
    Nic u nich Mars, chocia srogi,<br />
    I Achilles prędkonogi;<br />
    Ale śmiechy, ale żarty<br />
    Zwykły zbierać moje karty.<br />
    Pieśni, tańce i biesiady<br />
    Schadzają się do nich rady.<br />
    Statek tych czasów nie płaci,<br />
    Pracą człowiek próżno traci.<br />
    Przy fraszkach mi wżdy naleją,<br />
    A to wniwecz, co się śmieją.<br />
</p>