<h3>O żywocie ludzkim</h3>

<p>
    Fraszki to wszytko, cokolwiek myślemy,<br />
    Fraszki to wszytko, cokolwiek czyniemy;<br />
    Nie masz na świecie żadnej pewnej rzeczy,<br />
    Próżno tu człowiek ma co mieć na pieczy.<br />
    Zacność, uroda, moc, pieniądze, sława,<br />
    Wszystko to minie jako polna trawa;<br />
    Naśmiawszy się nam i naszym porządkom,<br />
    Wemkną nas w mieszek, jako czynią łątkom.<br />
</p>