<!DOCTYPE>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
<head>
    <title>Jan Kochanowski: Fraszki</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/style.css') ?>" />
</head>
<body>
<div id="pojemnik">
    <div id="naglowek">
        <h1>Jan Kochanowski</h1>
        <h2>Fraszki</h2>
        <ol id="menuglowne">
            <li><a href="<?php echo $this->url(array(), 'dogoscia') ?>">Do gościa</a></li>
            <li><a href="<?php echo $this->url(array(), 'naswojeksiegi') ?>">Na swoje księgi</a></li>
            <li><a href="<?php echo $this->url(array(), 'ozywocieludzkim') ?>">O żywocie ludzkim</a></li>
        </ol>
    </div>
    <div id="tresc">
        <?php echo $this->layout()->content; ?>
    </div>
    <div id="stopka">
        &copy;2010 Włodzimierz Gajda
    </div>
</div>
</body>
</html>