<!--//Przykład 10.1-->
<?php //echo $this->doctype() ?>
<!--<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">-->
<!--<head>-->
<!--    --><?php //echo $this->headTitle($this->tytul) ?>
<!--    --><?php //echo $this->headLink() ?>
<!--    --><?php //echo $this->headScript() ?>
<!--    --><?php //echo $this->headMeta() ?>
<!--</head>-->
<!--<body>-->
<!--<div id="pojemnik">-->
<!--    <h1 id="naglowek">Piosenki dla dzieci<span>&nbsp;</span></h1>-->
<!--    <ul id="menuglowne">-->
<!--        <li><a href="--><?php //echo $this->url(array(), 'misie') ?><!--">Jadą, jadą misie</a></li>-->
<!--        <li><a href="--><?php //echo $this->url(array(), 'kolko') ?><!--">Kółko graniaste</a></li>-->
<!--        <li><a href="--><?php //echo $this->url(array(), 'ojciec') ?><!--">Ojciec i syn</a></li>-->
<!--    </ul>-->
<!--    <div id="tresc">-->
<!--        --><?php //echo $this->layout()->content; ?>
<!--    </div>-->
<!--</div>-->
<!--</body>-->
<!--</html>-->


<!--Przykład 11-->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
<head>
    <?php echo $this->headTitle($this->tytul) ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headMeta() ?>
</head>
<body>
<div id="pojemnik">
    <h1 id="naglowek">Piosenki dla dzieci<span>&nbsp;</span></h1>
    <ul id="menuglowne">
        <li><a href="<?php echo $this->url(array(), 'misie') ?>">Jadą, jadą misie</a></li>
        <li><a href="<?php echo $this->url(array(), 'kolko') ?>">Kółko graniaste</a></li>
        <li><a href="<?php echo $this->url(array(), 'ojciec') ?>">Ojciec i syn</a></li>
    </ul>
    <div id="tresc">
        <?php echo $this->layout()->content; ?>
    </div>
</div>
</body>
</html>